pipeline:
  build:
    image: golang:1.20
    commands:
      - echo "Building app"
      - go mod tidy
      - go build -v .

  test:
    image: golang:1.20
    commands:
      - echo "Running tests..."
      - go test -v ./...


